### ISSUE TITLE
Trying to verify a contract in ropsten fails 

### ISSUE THREAD

**Issue by yann300** [Shard-Labs/remix-contract-getter#25]
contract : 0x96d87AB604AEC7FB26C2E046CA5e6eBBB9D8b74D
the API returns
```
[
  {
    "address": "0x96d87AB604AEC7FB26C2E046CA5e6eBBB9D8b74D",
    "status": "no match",
    "message": "\"Address for specified chain not found in repository\""
  }
]
```
although the contract is deployed

**Comment by edisinovcic** [comment]
This seems to be working with the latest changes: https://github.com/ethereum/remix-plugins-directory/pull/66

**Comment by edisinovcic** [comment]
Tested and it's working with latest changes.

**Comment by edisinovcic** [comment]
Closing this issue as it seems to be working now.
